-- MySQL Script generated by MySQL Workbench
-- 04/24/16 20:09:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema coderhub
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `coderhub` ;

-- -----------------------------------------------------
-- Schema coderhub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coderhub` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `coderhub` ;

-- -----------------------------------------------------
-- Table `coderhub`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coderhub`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `coderhub`.`users` (
  `id` BIGINT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `github_username` VARCHAR(45) NULL DEFAULT NULL,
  `auth_token` VARCHAR(45) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `birthday` DATE NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `street_address` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `phone_number` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `resume` BLOB NULL DEFAULT NULL,
  `fname` VARCHAR(45) NULL DEFAULT NULL,
  `lname` VARCHAR(45) NULL DEFAULT NULL,
  `profile_image_url` VARCHAR(100) NULL DEFAULT NULL,
  `is_admin` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `auth_token_UNIQUE` (`auth_token` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `coderhub`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coderhub`.`companies` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `coderhub`.`companies` (
  `id` BIGINT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `street_address` VARCHAR(100) NOT NULL,
  `owner` VARCHAR(45) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `coderhub`.`jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coderhub`.`jobs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `coderhub`.`jobs` (
  `id` BIGINT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` BIGINT(11) UNSIGNED NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `date_created` DATE NOT NULL,
  `date_expires` DATE NOT NULL,
  `job_description` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `DATE-PERIOD` (`date_created` ASC, `date_expires` ASC),
  INDEX `TITLE-COMP` (`company_id` ASC, `position` ASC),
  CONSTRAINT `c_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `coderhub`.`companies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `coderhub`.`applied_jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coderhub`.`applied_jobs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `coderhub`.`applied_jobs` (
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `job_id` BIGINT(20) UNSIGNED NOT NULL,
  `date_applied` DATETIME NOT NULL,
  INDEX `aj_uid_idx` (`user_id` ASC),
  INDEX `aj_jid_idx` (`job_id` ASC),
  CONSTRAINT `aj_uid`
    FOREIGN KEY (`user_id`)
    REFERENCES `coderhub`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `aj_jid`
    FOREIGN KEY (`job_id`)
    REFERENCES `coderhub`.`jobs` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `coderhub`.`company_admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coderhub`.`company_admins` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `coderhub`.`company_admins` (
  `user_id` BIGINT(11) UNSIGNED NOT NULL,
  `company_id` BIGINT(11) UNSIGNED NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  INDEX `ca_uid_idx` (`user_id` ASC),
  INDEX `ca_cid_idx` (`company_id` ASC),
  CONSTRAINT `ca_cid`
    FOREIGN KEY (`company_id`)
    REFERENCES `coderhub`.`companies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ca_uid`
    FOREIGN KEY (`user_id`)
    REFERENCES `coderhub`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `coderhub`.`connections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coderhub`.`connections` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `coderhub`.`connections` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id_requestor` BIGINT(11) UNSIGNED NOT NULL,
  `user_id_connection` BIGINT(11) UNSIGNED NOT NULL,
  `is_accepted` TINYINT(4) NULL DEFAULT '0',
  `is_blocked` TINYINT(4) NULL DEFAULT '0',
  PRIMARY KEY (`id`, `user_id_requestor`, `user_id_connection`),
  INDEX `connections_ibfk_1_idx` (`user_id_requestor` ASC),
  CONSTRAINT `connections_ibfk_1`
    FOREIGN KEY (`user_id_requestor`)
    REFERENCES `coderhub`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `connections_ibfk_2`
    FOREIGN KEY (`user_id_requestor`)
    REFERENCES `coderhub`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `coderhub`.`education_nodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coderhub`.`education_nodes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `coderhub`.`education_nodes` (
  `id` BIGINT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_name` VARCHAR(45) NOT NULL,
  `major` VARCHAR(45) NOT NULL,
  `minor` VARCHAR(45) NULL DEFAULT NULL,
  `degree_type` VARCHAR(45) NOT NULL,
  `gpa` FLOAT NULL DEFAULT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `SCHOOL` (`school_name` ASC, `major` ASC, `gpa` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `coderhub`.`hr_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coderhub`.`hr_users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `coderhub`.`hr_users` (
  `user_id` BIGINT(11) UNSIGNED NOT NULL,
  `company_id` BIGINT(11) UNSIGNED NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  INDEX `u_id_idx` (`user_id` ASC),
  INDEX `cm_id_idx` (`company_id` ASC),
  CONSTRAINT `cid`
    FOREIGN KEY (`company_id`)
    REFERENCES `coderhub`.`companies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `uid`
    FOREIGN KEY (`user_id`)
    REFERENCES `coderhub`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `coderhub`.`skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coderhub`.`skills` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `coderhub`.`skills` (
  `id` BIGINT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `coderhub`.`user_education_nodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coderhub`.`user_education_nodes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `coderhub`.`user_education_nodes` (
  `user_id` BIGINT(11) UNSIGNED NOT NULL,
  `education_node_id` BIGINT(11) UNSIGNED NOT NULL,
  INDEX `uen_uid_idx` (`user_id` ASC),
  INDEX `uen_enid_idx` (`education_node_id` ASC),
  CONSTRAINT `uen_enid`
    FOREIGN KEY (`education_node_id`)
    REFERENCES `coderhub`.`education_nodes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `uen_uid`
    FOREIGN KEY (`user_id`)
    REFERENCES `coderhub`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `coderhub`.`user_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coderhub`.`user_skills` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `coderhub`.`user_skills` (
  `user_id` BIGINT(11) UNSIGNED NOT NULL,
  `skills_id` BIGINT(11) UNSIGNED NOT NULL,
  INDEX `u_id_idx` (`user_id` ASC),
  INDEX `s_id_idx` (`skills_id` ASC),
  CONSTRAINT `s_id`
    FOREIGN KEY (`skills_id`)
    REFERENCES `coderhub`.`skills` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `u_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `coderhub`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `coderhub`.`work_nodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coderhub`.`work_nodes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `coderhub`.`work_nodes` (
  `id` BIGINT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(45) NOT NULL,
  `company_id` BIGINT(11) UNSIGNED NULL DEFAULT NULL,
  `position` VARCHAR(45) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `COMPANY` (`company_name` ASC, `position` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `coderhub`.`user_work_nodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coderhub`.`user_work_nodes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `coderhub`.`user_work_nodes` (
  `user_id` BIGINT(11) UNSIGNED NOT NULL,
  `work_node_id` BIGINT(11) UNSIGNED NOT NULL,
  INDEX `uwn_uid_idx` (`user_id` ASC),
  INDEX `uwn_wnid_idx` (`work_node_id` ASC),
  CONSTRAINT `uwn_uid`
    FOREIGN KEY (`user_id`)
    REFERENCES `coderhub`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `uwn_wnid`
    FOREIGN KEY (`work_node_id`)
    REFERENCES `coderhub`.`work_nodes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `coderhub`.`users_following_companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coderhub`.`users_following_companies` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `coderhub`.`users_following_companies` (
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `company_id` BIGINT(20) UNSIGNED NOT NULL,
  INDEX `u_id_idx` (`user_id` ASC),
  INDEX `c_id_idx` (`company_id` ASC),
  CONSTRAINT `ufid`
    FOREIGN KEY (`user_id`)
    REFERENCES `coderhub`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cfid`
    FOREIGN KEY (`company_id`)
    REFERENCES `coderhub`.`companies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
